# Generated by Django 5.1.1 on 2024-11-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='s3_photourl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
