# Generated by Django 5.1.1 on 2024-11-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='s3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
