# Generated by Django 5.1.1 on 2024-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
