# Generated by Django 5.1.1 on 2024-11-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlist_playlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlist/'),
        ),
    ]
