# Generated by Django 5.1.1 on 2024-11-03 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_playlist_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
